import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import * as material_icon from '@material/icon-button/index';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>

        <title>StarbucksStudy</title>
        <meta name="description" content="Generated by create next app" />
        {/*--Open Graph 부분--*/}
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Apple (KR)" />
        <meta property="og:title" content="iPad 10.2" />
        <meta property="og:description" content="강력한 A13 Bionic 칩을 탑재한 iPad. 센터 스테이지 기술이 적용된 12MP 울트라 와이드 전면 카메라, True Tone 디스플레이 기술 및 64GB 저장 용량까지 갖췄습니다." />
        <meta property="og:image" content="/images/ipad-seo.png" />
        <meta property="og:url" content="https://www.apple.com/kr/ipad-10.2/" />

        {/*--twitter card 부분--*/}
        <meta property="twitter:card" content="summary" />
        <meta property="twitter:site" content="Apple (KR)" />
        <meta property="twitter:title" content="iPad 10.2" />
        <meta property="twitter:description" content="강력한 A13 Bionic 칩을 탑재한 iPad. 센터 스테이지 기술이 적용된 12MP 울트라 와이드 전면 카메라, True Tone 디스플레이 기술 및 64GB 저장 용량까지 갖췄습니다." />
        <meta property="twitter:image" content="/images/ipad-seo.png" />
        <meta property="twitter:url" content="https://www.apple.com/kr/ipad-10.2/" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <main className={styles.main}>
          Hello wlrd!
        </main>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

    </div>
  )
}
